"use client"
import React, { useEffect, useState } from 'react'
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles'
import theme from '../../theme'
import cloudbase from '@cloudbase/js-sdk';

const inter = Inter({ subsets: ['latin'] })

export const globalContext = React.createContext({});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const postMsg = (pluginMessage) => {
  let pluginId = { pluginId: '*' };
  let originUrl = 'https://js.design';
  switch ('1') {
    //Figma
    case 'figma':
      pluginId = { pluginId: '*' };
      originUrl = '*';
      break;
    case 'mg':
      pluginId = {};
      originUrl = '*';
      break;
    case 'pixso':
      pluginId = {};
      originUrl = '*';
      break;
    default:
      break;
  }
  window.parent.postMessage(
    {
      pluginMessage: pluginMessage,
      ...pluginId,
    },
    originUrl
  );
}

export default function RootLayout({ children }) {

  const [app, setApp] = useState(null)

  useEffect(() => {
    const ENV = 'TEST'; //测试环境
    // const ENV = 'PRODUCTION'; //正式环境
    const envId = ENV === 'TEST' ? 'inspiration-test-2f7mtqq233061d9' : 'inspiration-9g1159fid21da3f2'
    const app = cloudbase.init({
      env: envId
    });
    const auth = app.auth();
    async function login() {
      await auth.signInAnonymously();
      const loginScope = await auth.loginScope();
      // 如为匿名登录，则输出 true
      console.log(loginScope === 'anonymous');
    }
    //匿名登录
    login();
    setApp(app)
  }, [])

  return (
    <html lang="en">
      <globalContext.Provider
        value={{
          // pla: pla,
          // openid: openid,
          // setOpenid: setOpenid,
          app: app,
          postMsg: postMsg
        }}>
        <ThemeProvider theme={theme}>
          <body className={inter.className}>{children}</body>
        </ThemeProvider>
      </globalContext.Provider>
    </html>
  )
}