"use client"
import React from 'react'
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@mui/material/styles'
import theme from '../../theme'

const inter = Inter({ subsets: ['latin'] })

export const globalContext = React.createContext({});
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const postMsg = (pluginMessage) => {
  let pluginId = { pluginId: '*' };
  let originUrl = 'https://js.design';
  switch ('1') {
    //Figma
    case 'figma':
      pluginId = { pluginId: '*' };
      originUrl = '*';
      break;
    case 'mg':
      pluginId = {};
      originUrl = '*';
      break;
    case 'pixso':
      pluginId = {};
      originUrl = '*';
      break;
    default:
      break;
  }
  window.parent.postMessage(
    {
      pluginMessage: pluginMessage,
      ...pluginId,
    },
    originUrl
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <globalContext.Provider
        value={{
          // pla: pla,
          // openid: openid,
          // setOpenid: setOpenid,
          // app: app,
          postMsg: postMsg
        }}>
        <ThemeProvider theme={theme}>
          <body className={inter.className}>{children}</body>
        </ThemeProvider>
      </globalContext.Provider>
    </html>
  )
}